server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /

spring:
  config:
    activate:
      on-profile: local
    use-legacy-processing: true

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}
  kafka:
    bootstrap-servers: 15.164.21.79:9092
    consumer:
      #bootstrap-servers: 15.164.21.79:9092
      group-id: kafka-one
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      #bootstrap-servers: 15.164.21.79:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


logging.level:
  org.hibernate.sql: debug


