server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /

spring:
  config:
    activate:
      on-profile: local

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}


profiles:
  include: oauth


logging.level:
  org.hibernate.sql: debug

