server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_DATASOURCE_URL}
    username: ${PROD_DATASOURCE_USERNAME}
    password: ${PROD_DATASOURCE_PASSWORD}

  profiles:
    include: oauth

logging.level:
  org.hibernate.sql: debug

springdoc:
  api-docs:
    enabled: false